#spring:
#  profiles:
#    active: local
#    include: real-oauth
#  session:
#    store-type: jdbc
#  datasource:
#    platform: h2
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: H2
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#

spring:
  profiles:
    active: local
    include: real-oauth

  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: junzz1324##
    url: jdbc:mysql://localhost:3306/jpaexampleNK?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=UTC
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: create


